name: Weather Dashboard

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build -- --configuration production --base-href /LabDeployement/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Build Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/LabDeployement

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4